### ISSUE TITLE
Show recent chats

### ISSUE THREAD

**Issue by amandhamija98** [rpotter12/whatsapp-play#299]
We could show the recent chats either as a part of wchat script itself (before target search is fired)
or as a separate script

**Comment by amandhamija98** [comment]
May I be work on this?

**Comment by xandao6** [comment]
How do you pretend to show the recent chats? Why it will be useful @amandhamija98 ?

**Comment by amandhamija98** [comment]
So what I was thinking was, we could show the name and the last message of the recent chats. By recent chats I mean the top few chats that are visible when one opens whatsapp web.

It will be useful because often we do not have a target in mind before messaging them. Sometimes we see our recent chats (which may be unread) and then decide to reply to them.
We could also segregate the unread and read chats that are recent

**Comment by xandao6** [comment]
@rpotter12 What do you think?

**Comment by rpotter12** [comment]
> So what I was thinking was, we could show the name and the last message of the recent chats. By recent chats I mean the top few chats that are visible when one opens whatsapp web.
> 
> It will be useful because often we do not have a target in mind before messaging them. Sometimes we see our recent chats (which may be unread) and then decide to reply to them.
> We could also segregate the unread and read chats that are recent

I think this will be a good idea. :)

**Comment by rpotter12** [comment]
This idea will be more useful when show some recent chats of the particular person. Otherwise showing the recent chats of different persons will not be a useful idea.:)

**Comment by SinghHimadri** [comment]
@rpotter12  But in the issue it was written if whatsappweb view could be attained. Because initially if we don't have the target in mind so we can have a look at this list and then decide the target. The feature I have added shows all recent chats if it's target specific then we need to know the target beforehand.I did what was mentioned. Please elaborate what needs to be done I'll modify still I think  being target specific is not that usefull.
